### ISSUE TITLE
CD via travis?

### ISSUE THREAD

**Issue by tsaleh** [pivotal/blog#11]
Setup travis to automatically push any changes to this repo.  Make sure the creds are stored in lastpass.

**Comment by tsaleh** [comment]
http://discuss.gohugo.io/t/automated-hugo-deployments-anywhere-using-wercker/539

**Comment by williammartin** [comment]
I think maybe only people with rights to this repo can do this work, not as a pull requests as Travis encrypted credentials are tied to a specific repo?

**Comment by tsaleh** [comment]
Should have closed this, as I did it last weekend (!!!).  See the README for a quick description.
