### ISSUE TITLE
Question on Distributed Elixir post

### ISSUE THREAD

**Issue by tonyvanriet** [pivotal/blog#126]
Hi @benjamintanweihao,

I’m just getting started with building up a distributed Elixir cluster, and [your post](http://engineering.pivotal.io/post/how-to-set-up-an-elixir-cluster-on-amazon-ec2/) has been a big help. Thank you.

You mentioned in the article that Distillery wasn’t working for you. I’m curious what kind of problems you ran into there, as we’re using Distillery and I’m hoping I’m not walking into a dead end.

I’ve just recently had success using Distillery and edeliver's `LINK_VM_ARGS` to configure the node name. To get there I had to add edeilver's [LinkConfig plugin](https://github.com/boldpoker/edeliver/blob/master/lib/distillery/plugins/link_config.ex#L13) to the Distillery config, which I don't believe is mentioned in any of the documentation. Without this, the release package included the default generated `vm.args` instead of the symbolic link. I'm hoping this is the issue you ran into and I can rest assured.

**Comment by benjamintanweihao** [comment]
Ohai @tonyvanriet ! It could be just that! I think when I was messing around with Distillery at that time, it was still pretty new, or I was pretty stupid and missed out something completely obvious. I fiddled around with a few other options and only had luck with edeliver. So no, I don't think you have anything to worry about if you managed to get things up and running.
