### ISSUE TITLE
Author page simple UI updates 

### ISSUE THREAD

**Issue by Lindsayauchin** [pivotal/blog#146]
## Proposal:
Simple UI updates to the CSS to the raw elements in the container that current holds the Authors information. 

See example`http://engineering.pivotal.io/authors/kyle/`

1. Remove author from the marketing header image and add 'Author' heading below (possibly need to address navigation and information hierarchy of the blog in another request)
2. Add icons beside twitter and GitHub handle - reduce space for 'twitter' and 'GitHub' label and these icons are easily recognizable at a glance s no need to spell it out. 
3.  Add tile to the list of articles to give users more feedback and differentiation from the list on the 'home page'

![author_page](https://cloud.githubusercontent.com/assets/27746614/25749425/85d0a8f6-317c-11e7-814d-4cef9ca60ca6.jpg)

**Comment by osis** [comment]
@ascherbaum-pivotal what do you think?

**Comment by ascherbaum-pivotal** [comment]
I like it!

Maybe put a web globe in front of the blog links as well?
