### ISSUE TITLE
Automated Tweets announcing articles should mention authors

### ISSUE THREAD

**Issue by osis** [pivotal/blog#155]
I'm not quite sure how to do this. I was wondering about hijacking the author field in the rss feed (https://github.com/pivotal/blog/issues/139) but I'm not sure that's the best approach.

**Comment by ascherbaum-pivotal** [comment]
The author or authors are listed in the header of the document. Just pull it from there (and from there you can lookup the Twitter handles as well).

**Comment by osis** [comment]
It means we'll need to make another app that watches the blog and posts to Twitter? Or is there a more graceful way to integrate with Hugo?

Would be great to use something like IFTTT to keep maintenance overhead low.

**Comment by osis** [comment]
For example, automated Tweet currently look like [this](https://twitter.com/pivotaleng/status/856608968260689920) when it would be nice if they looked more like [this](https://twitter.com/pivotaleng/status/856608968260689920)

**Comment by ascherbaum-pivotal** [comment]
Not sure you can do this with IFTTT ... I rather doubt it.
