### ISSUE TITLE
Open Graph Support

### ISSUE THREAD

**Issue by osis** [pivotal/blog#161]
For richer links, SEO, etc.

![screen shot 2017-06-07 at 10 54 36 am](https://user-images.githubusercontent.com/347097/26885146-cc630d06-4b6f-11e7-994c-88767eec8bac.png)

**Comment by textbook** [comment]
I could have a go at this, I have done it recently in Jinja for a Pelican theme (https://github.com/textbook/bulrush/blob/master/bulrush/templates/meta_tags.html). It would be nice to get good results on:

 - https://search.google.com/structured-data/testing-tool
 - https://cards-dev.twitter.com/validator
 - https://developers.facebook.com/tools/debug
