### ISSUE TITLE
There should be sharing options beyond Twitter

### ISSUE THREAD

**Issue by osis** [pivotal/blog#167]
We should start looking beyond Twitter as a way to share our content! 

I think the requirement to @ folks when Twitter sharing should stay, but we can allow the other mediums to join in the fun. Bonus points if we can figure out a way to mention the author on those networks as well.

![screen shot 2017-07-11 at 4 33 49 pm](https://user-images.githubusercontent.com/347097/28089387-d98d6592-6656-11e7-9430-9e3b1b47def7.png)

**Comment by xtremerui** [comment]
I am working on this as flex hour project.

**Comment by osis** [comment]
Very true.
