### ISSUE TITLE
Image Assets for Blog Posts

### ISSUE THREAD

**Issue by cunnie** [pivotal/blog#212]
This is NOT an issue.

I am using this Issue as a mechanism to store images for blog posts so that I don't bloat the repo by storing images there.

![duet_gpg_1](https://user-images.githubusercontent.com/1020675/46825298-29f40f00-cd48-11e8-9bae-b703874a4bca.png)

![new_gpg_key](https://user-images.githubusercontent.com/1020675/46839459-e236ad00-cd72-11e8-89b3-ca37e403769a.png)

![unverified](https://user-images.githubusercontent.com/1020675/46839601-828cd180-cd73-11e8-88bf-3cc389c65fc5.png)

**Comment by osis** [comment]
Nice!
