### ISSUE TITLE
Support multiple authors or co-authors

### ISSUE THREAD

**Issue by wfernandes** [pivotal/blog#25]
Could we specify a co-author with the blog author. So their name shows up at the top as well.

**Comment by tsaleh** [comment]
Yeah, I think that'd be possible.   [The author snippet is here](https://github.com/pivotal/blog/blob/fe5c96677a25f2d5d954d16e7960e88d70be5960/themes/pivotal-ui/layouts/_default/single.html#L19):

```
{{ with (index .Site.Data.authors (lower .Params.author)) }}
by
<a href="https://twitter.com/{{ index . "Twitter" }}">
  {{ index . "Name" }}
</a>
{{ end }}
```

It references the files in [/data/authors/](https://github.com/pivotal/blog/tree/fe5c96677a25f2d5d954d16e7960e88d70be5960/data/authors) using the `author` key [in the header](https://github.com/pivotal/blog/blame/fe5c96677a25f2d5d954d16e7960e88d70be5960/archetypes/post.md#L4).  I think you'd have to change that `author` key to be an array (it's just yaml), and then change the snippet to deal with either single or multiple authors.

I'd gladly pull in such a PR, but it's not something I've got time to do, myself.

**Comment by wfernandes** [comment]
Closing this issue since PR was merged in [here](https://github.com/pivotal/blog/pull/31)
