### ISSUE TITLE
Broken image on Firehose-Plugin post

### ISSUE THREAD

**Issue by menicosia** [pivotal/blog#38]
http://engineering.pivotal.io/post/Firehose-Plugin/

In-between "What is the firehose?" and "How can I obtain admin access?" headers.

-- Marco N.

**Comment by nertzy** [comment]
It's not broken for me.

**Comment by Jim-Campbell** [comment]
Me either. Marco, I'm closing it.

**Comment by menicosia** [comment]
Huh. Yeah, I see the image now as well. I have no idea what changed. I obviously had sufficient network access to file a GitHub issue about it... :)

Leaving closed!
