### ISSUE TITLE
Rethinking criteria for accepting pull requests?

### ISSUE THREAD

**Issue by lkogler** [pivotal/blog#39]
@pivotal/engineering-directors I'm wondering if we should revisit the submission / acceptance process for contributing to this blog. 

I appreciate the desire to have high quality blog posts, but I also thought that the reason for starting this blog was so that we would have a less onerous approval process to get things posted (and therefore have higher participation rates).

I can't help but notice that there are currently 6 open pull requests that appear to be ready to publish but have not been accepted.  Some of them have been open for nearly a month.  I'm afraid that having a lengthy review process with a lot of back and forth will discourage people from using this platform for their blog posts.  I've already heard it suggested that we could just post to Medium instead (as the PMs and designers have started doing).

If we want this blog to be an active, thriving forum that people want to contribute to, I think we should reconsider the pull request policy to make it easier and faster to get content published.

**Comment by mkocher** [comment]
:+1:

I don't see any reason that engineering directors should be gatekeepers. I think we should move to our normal pattern for code: either pair on the blog post, or get a plus one from one other person. I'm willing to be convinced that even that is too much process and we should move to anyone being able to commit anything.

**Comment by ajackson** [comment]
I agree we want as little impediments as possible, otherwise folks will just publish to their own blog or won't write post at all.   I'd rather have the occasional mistakenly published incoherent blog post than slow them down.   Can we just have folks commit to master and then setup a concourse pipeline to publish to the site a few times a day or even on every change (I think there's a name for that)?

**Comment by tsaleh** [comment]
But!  But, chaos!!

Srsly, though, this is a good idea.  Unless someone gets to it first, I'll
try to take care of it over the weekend.

-- 
Cheers,
Tammer

Sent from my iPhone.

**Comment by tsaleh** [comment]
So I _think_ this is done.  I've 

1. setup travis to CD to both production and to staging (where we show drafts)
1. merged all the outstanding PRs
1. updated the README with the new process and some writing tips
1. opened this repo for write access to all pivots

However, I totally don't expect that the github teams are up to date, so we should expect some pivots to have to request access.

Thanks @lkogler - this is much better.

**Comment by lkogler** [comment]
Awesome, thanks @tsaleh for taking care of that so quickly!
