### ISSUE TITLE
weerd artifacts in 2000 vms post

### ISSUE THREAD

**Issue by tsaleh** [pivotal/blog#41]
@Kaixiang can you fix the strange artifacts in [the 2000 vms post](http://engineering.pivotal.io/post/Scaling-up-to-2000-vms-with-BOSH/)?  Seeing lots of words like `donâ€™t`.

**Comment by nertzy** [comment]
This could be reverted to get the better "smart" apostrophes now that we have valid HTML5 with the UTF-8 charset. #48

**Comment by tsaleh** [comment]
Sounds good - you should have access to push to master.

Cheers,
Tammer Saleh
Director of Engineering, Pivotal CF, London
http://pivotal.io | http://tammersaleh.com | +44 7463 939332
