### ISSUE TITLE
Engineering blog not appearing in Google SERP

### ISSUE THREAD

**Issue by menicosia** [pivotal/blog#43]
https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=pivotal%20engineering%20blog

It's pretty odd that the GitHub site for the blog is result #5, but the blog itself does not appear at all.

I thought it might have been a `robots.txt` issue or similar, but lo, we appear as result #1 if you search for 'pivotal engineering journal':

https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=pivotal+engineering+journal

Perhaps some SEO is appropriate here, since more people are going to search and discover this site by looking for the term 'blog' than 'journal.'

**Comment by tsaleh** [comment]
Time passes, Google catches up...

![pivotal engineering blog - google search 2016-04-22 4 pm-03-18](https://cloud.githubusercontent.com/assets/2016/14745546/b67c3432-08a3-11e6-8ee8-bbcb06097ade.png)
