### ISSUE TITLE
encoding issues on http trailers page

### ISSUE THREAD

**Issue by mikfreedman** [pivotal/blog#46]
http://engineering.pivotal.io/post/http-trailers/

![screen shot 2015-12-15 at 10 37 48 am](https://cloud.githubusercontent.com/assets/1176640/11797560/eb03480e-a317-11e5-9df1-6ea01054c6cd.png)

see attached.

**Comment by nertzy** [comment]
Fixed by #48

**Comment by mikfreedman** [comment]
@nertzy :+1:
