### ISSUE TITLE
Find a good name

### ISSUE THREAD

**Issue by tsaleh** [pivotal/blog#5]
Random ideas:

* [Meteorologica](https://en.wikipedia.org/wiki/Meteorology_(Aristotle))

[Source for other ideas](https://en.wikipedia.org/wiki/Cloud)

From my friend Dan:
* Dragonfire (awesome shit that comes out of clouds)
* The Care Bears live in a faraway place up in the clouds called **Care-a-Lot**, which constitutes a part of the Kingdom of Caring.
* Cloud City
* Inner Core (the center of the earth)
* Atmosphere
* Atmospheric
* Atmos
* Sphere
* Climate Change
* Climatology
* Water Cycle (Clouds are one piece of a larger, cyclic process, much like... Agile Software Development)
* Condensation (the process of the ocean becoming clouds)
* Precipitation (the stuff that comes out of clouds)
* Rain and Snow (simpler words for saying Precipitation)
* Zoom Zoom and Boom Boom (the sights and sounds of lightning and thunder coming out of clouds)
* Lightning and Thunder
* Thunderbolt
* Bolt

**Comment by tsaleh** [comment]
@pivotal-cf/engineering-directors Any other ideas?

**Comment by flavorjones** [comment]
"Pivotal Cloud Foundry Engineering Blog"

**Comment by tsaleh** [comment]
![giphy-3](https://cloud.githubusercontent.com/assets/2016/9760327/efc72d9c-56eb-11e5-8d7b-ce003bc84430.gif)

**Comment by flavorjones** [comment]
As someone who once had not one, but two libraries in a Top Ten List of
poorly named gems[1], I urge you to reconsider cleverness as a requirement.


  [1]:
http://unethicalblogger.com/2011/11/13/ten-poorly-chosen-gem-names.html
(under the "Just Plain Stupid" heading)

**Comment by tsaleh** [comment]
Well, at least you didn't make the "Probably Offensive" list.  However, gems are different than blogs.  The thoughtbot blog became famous partially because of the "GIANT ROBOTS SMASHING INTO OTHER GIANT ROBOTS" title.

**Comment by flavorjones** [comment]
[image: Inline image 1]

**Comment by flavorjones** [comment]
![jack-disbelief](https://cloud.githubusercontent.com/assets/8207/9761678/3ff75c80-56cc-11e5-8f01-485d83606ea5.gif)

**Comment by Osis** [comment]
You call those bad?

- Delassio & friends
- Tammer & friends
- Cloud Twerking: how to do it right
- The Cloud Train: How to keep running
-

**Comment by Osis** [comment]
Oops. Fat fingers on my phone. Wasn't done...

**Comment by tsaleh** [comment]
* Smog
* Cloudy Day
* Floating Water

**Comment by Osis** [comment]
- Hurricane (Pivoting Clouds)
- Water Cycle? (Clouds, Condensation, Evaporation)
- Interstellar Clouds? (https://en.wikipedia.org/wiki/Interstellar_cloud)

**Comment by Osis** [comment]
Code/eng Foundry

**Comment by tsaleh** [comment]
Pivoting Clouds?

**Comment by tsaleh** [comment]
Cloudy with a Chance of Engineering?
