### ISSUE TITLE
List of authors missing

### ISSUE THREAD

**Issue by ascherbaum-pivotal** [pivotal/blog#57]
Blogs usually have a way to quickly navigate to the list of authors, and/or to a specific author.

**Comment by andreasscherbaum** [comment]
With the last update (in issue #139) the author no longer links to the Twitter account, but to a page on the blog for the author - which does not exist:

http://engineering.pivotal.io/categories/postgresql/

**Comment by osis** [comment]
Does your author PR https://github.com/pivotal/blog/pull/145 satisfy this?

**Comment by ascherbaum-pivotal** [comment]
Sure it does, thanks for following up.
