### ISSUE TITLE
Site title missing from <title> element of article pages

### ISSUE THREAD

**Issue by nertzy** [pivotal/blog#67]
In #61 the duplicate site title was removed from the blog index page. This had the effect of removing the site title entirely from article pages.

For example, http://engineering.pivotal.io/post/gporca-open-source/ currently has 

``` html
<title> GPORCA, A Modular Query Optimizer, Is Now Open-Source </title>
```

 whereas before it had something like

``` html
<title> GPORCA, A Modular Query Optimizer, Is Now Open-Source &middot; Pivotal Engineering Journal </title>
```

We should figure out a solution that keeps the site title on article pages but doesn't double it on article pages.

**Comment by mcwumbly** [comment]
this looks OK to me now

```html
<title> GPORCA, A Modular Query Optimizer, Is Now Open-Source · Pivotal Engineering Journal </title>
```
