### ISSUE TITLE
Add a hiring link on Eng Blog

### ISSUE THREAD

**Issue by nachtigal** [pivotal/blog#86]
It'd be nice to have a link to [our hiring page](pivotal.io/careers) in the top right of the blog that's present on every page. Thinking practically, a lot of the devs coming to this blog will be good, the type we want to hire, and a little button in the corner will remind them. Uber does this on their eng blog.

**Comment by osis** [comment]
Great suggestion. Would you be willing to send a PR to add the link to the header?

**Comment by ascherbaum-pivotal** [comment]
You want to look into either themes/pivotal-ui/layouts/partials/head.html or  themes/pivotal-ui/layouts/partials/heading.html for this addition.
