### ISSUE TITLE
Design consistency for Eng blog

### ISSUE THREAD

**Issue by nachtigal** [pivotal/blog#88]
It'd be nice for the eng blog to have some design consistency with the rest of Pivotal UI. I'm not saying this needs to look like the corporate site at all, but it should look familiar.

Tammer mentioned there might be an update to the Pivotal UI that we could use, and also, there's a template we could take from that's being used on the PWS blog: https://blog.run.pivotal.io/another-drop-of-spring-is-here/

**Comment by osis** [comment]
Good news! @Lindsayauchin is going to take a look at the site and suggest some tweaks.
